### ISSUE TITLE
GetItem() increments lockId preventing long-running process that locked session from writing to it

### ISSUE THREAD

**Issue by judowalker** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#9] opened 2016-12-12 22:28 UTC
I have a long-running process that locks session. While that process is running, I have some ajax requests that obtain a read-only copy of session (via `[SessionState(SessionStateBehavior.ReadOnly)]
`). However, this causes `lockId` to increment which prevents the long-running process from writing to session.

Maybe only increment `lockId` if `lockRecord` is true?

**Comment by MarkCBB** [comment] 2016-12-13 19:11
Ok, I'll take a look. First I'll try to reproduce in a test case.

**Comment by MarkCBB** [comment] 2016-12-14 08:34
I can't reproduce the issue in a test case. Could you take a look at the new test case created in the issue branch? The second and third commits contain the implementations. You know better the issue than I and you may see some missing things in my implementation.

**Comment by judowalker** [comment] 2016-12-14 17:54
I'll take a look.

**Comment by MarkCBB** [comment] 2016-12-15 23:01
First, thank you for your collaboration. The test case reproduced the issue perfectly and looks much better with async and await.

I think that with my small change this issue is going to be solved. The solution seems to be simple (may be too much simple). Anyway, all test cases are passed including the ones that you developed.

I'll put a development version of the package with the change. If you have you own test cases in your project could be nice to know if everything is working as expected downloading and testing the pre-release. By my side, I'll take a look again to the changed function and wait for your feedback to publish the final release.

**Comment by MarkCBB** [comment] 2016-12-15 23:01
Sorry, closed by mistake.

**Comment by judowalker** [comment] 2016-12-16 07:30
It definitely works. I made the same change locally before submitting the issue and it worked as expected when used in my projects. The tests passed as well.

**Comment by MarkCBB** [comment] 2016-12-16 18:12
Great! I'll put the final release in nuget tomorrow.

**Comment by MarkCBB** [comment] 2016-12-17 20:06
The package is already published since this morning. If you want I can mention you in the about section as collaborators, is the minimum courtesy for people that have collaborated improving this project.

**Comment by judowalker** [comment] 2016-12-17 20:55
Thanks for fixing this. I just installed the new package.

**Comment by MarkCBB** [comment] 2016-12-18 12:17
You're welcome. There it goes the mention. https://github.com/MarkCBB/MongoDB-ASP.NET-Session-State-Store/wiki#about

**Closed as completed by MarkCBB** 2016-12-18 12:17 UTC
